/**
 * The detailCtrl controls the template which displays 
 * information about individual search results.
 * This page is linked to dynamically from the search 
 * results and makes an API call  to getDetails on initialization.
 * 
 * @prop vm.date - the date string selected (from next 7 days) in the add to diary widget
 * @prop vm.dates - an array of dates generated by the datetimeHelperService to populate the select element
 * @prop vm.hour - the hour string selected by the user in the diary widget 
 */

'use strict';

const DetailCtrl = function($routeParams, datetimeHelperService, googleApiService, helperService) {
  var vm = this;

  vm.amPm = 'PM';
  vm.date = 'today';
  vm.dates;
  vm.hour = '1.00';
  vm.hours;
  vm.placeid = $routeParams.placeid || null;
  vm.photoref = $routeParams.photoref || null;
  vm.starRating = {int: [], dec: []};
  vm.result;

  vm.addToDiary = addToDiary;
  
  function init() {
    console.log(vm.placeid, vm.photoref);
    vm.dates = datetimeHelperService.getNextWeek();
    vm.hours = datetimeHelperService.getHours();
    // getDetails(vm.placeid, vm.photoref);
  }

  function getDetails(placeid, photoref) {
    googleApiService
      .getDetails(placeid, photoref)
      .then(result => {
        // vm.result = result;
        console.log({result});
        vm.result = helperService.formatHours(helperService.formatTags(result)[0]);
        vm.starRating = helperService.createStarRating(result.rating);
        console.log({result});
      })
      .catch(err => console.log({ err }));  
  }

  function addToDiary() {
    console.log(vm.date);
    console.log(vm.hour);
  }


  init();
}

pathFinderApp.controller('detailCtrl', [
  '$routeParams', 
  'datetimeHelperService',
  'googleApiService', 
  'helperService',
  DetailCtrl
]);